### ISSUE TITLE
Fix abi build error

### ISSUE THREAD

**Issue by guoyunhe** [amilajack/erb-node-opencv-example#1]
https://github.com/amilajack/erb-node-opencv-example/blob/99856b4d062aceed3f156c0b4c5fb850e94b78f8/app/package.json#L13

I found that, if you modify the `--target=1.6.6` to the actual Electron version in your project, it works. However, I can only make it work with npm, not yarn.

**Comment by amilajack** [comment]
Then that means this is probably a bug with yarn. Try `rm -rf node_modules && yarn`. Will fail if already built
